name: Android Release APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant Permission to Gradle
      run: chmod +x gradlew

    - name: 🔍 List all available Gradle tasks
      run: ./gradlew tasks --all

    - name: Build Release APK
      run: ./gradlew :androidApp:assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: androidApp/build/outputs/apk/release/*.apk
